### ISSUE TITLE
checklist for future workshops (from pilot repo)

### ISSUE THREAD

**Issue by nehamoopen** [nehamoopen/worcshop-book#5]
See: https://github.com/nehamoopen/workshop-worcs-pilot/issues/2#issue-1115292604

- [ ]  provide participants with handout / checklist / issue template (if such a thing exists) of the phases + steps
- [ ]  an introduction video
- [ ]  an introductory presentation
- [ ]  a tutorial video
- [ ]  a presentation of the phases / steps
- [x]  bookdown upgrade
- [ ]  adapt workshop program based on feedback
- [ ]  demo project (data, code, text, references) for those without their own research projects
- [ ]  alternative instructions for those without access to Git (e.g. participants from UMCU)
